( This gcode generated by C:/Program Files (x86)/EAGLE-6.4.0/ulp/pcb-gcode.ulp )
( Copyright 2005 by John Johnson. See readme.txt for licensing terms. )

G21

G90
G00 Z12.7000 
G00 X0 Y0
M03
G04 P3.000000
(File Footer)
G00 Z12.7000 
M05
M02
